### PR TITLE
Add new Endpoints and refactor some duplicate lines.

### PR DESCRIPTION
**Pull request by oedm**
Hi @meshfields,
I've added two new endpoints `/namespaces` and `/{NAMESPACE}/deployments`.
I could also fix the hardcoded default namespace to use the requested namespace parameter instead.

Please take a look and let me know, if you see any issues.

Thanks!
Marcel

### CODE REVIEW

**Comment by oedm** [comment]
i've added an commit to fix the merge conflict.

**Comment by meshfields** [comment]
Looking good. Thanks!

**Comment by meshfields** [comment]
me noob

**Comment by oedm** [comment]
Me noob too. My fork was behind your repo. Could fix that, but `npm test` fails. I'll try to align my code.

**Pull request merged**
